### ISSUE TITLE
Wrong image step

### ISSUE THREAD

**Issue by Zumbalamambo** [Qualeams/Android-Face-Recognition-with-Deep-Learning-Library#6]
Getting the following error in Lenovo mobile

> 05-21 16:42:59.568 7583-7725/com.eigenfaces E/cv::error(): OpenCV Error: Image step is wrong (The matrix is not continuous, thus its number of rows can not be changed) in cv::Mat cv::Mat::reshape(int, int) const, file /build/master_pack-android/opencv/modules/core/src/matrix.cpp, line 1047
> 05-21 16:42:59.568 7583-7725/com.eigenfaces E/org.opencv.core.Mat: Mat::n_1reshape__JII() caught cv::Exception: /build/master_pack-android/opencv/modules/core/src/matrix.cpp:1047: error: (-13) The matrix is not continuous, thus its number of rows can not be changed in function cv::Mat cv::Mat::reshape(int, int) const
> 05-21 16:42:59.568 7583-7725/com.eigenfaces E/AndroidRuntime: FATAL EXCEPTION: Thread-6776
>                                                               Process: com.eigenfaces, PID: 7583
>                                                               CvException [org.opencv.core.CvException: cv::Exception: /build/master_pack-android/opencv/modules/core/src/matrix.cpp:1047: error: (-13) The matrix is not continuous, thus its number of rows can not be changed in function cv::Mat cv::Mat::reshape(int, int) const
>                                                               ]
>                                                                   at org.opencv.core.Mat.n_reshape(Native Method)
>                                                                   at org.opencv.core.Mat.reshape(Mat.java:655)
>                                                                   at com.eigendetector.Recognition.Eigenfaces.addImage(Eigenfaces.java:179)
>                                                                   at com.eigenfaces.TrainingActivity$1.run(TrainingActivity.java:107)
>                                                                   at java.lang.Thread.run(Thread.java:818)
>

**Comment by sladomic** [comment]
@Zumbalamambo there seemd to be an issue with the image file. Check the training images or try to debug before the code enters the addImage function of Eigenfaces.

**Comment by Zumbalamambo** [comment]
Ok it worked. Thank you

**Comment by sunnykinger** [comment]
@Zumbalamambo how did you solve the problem?
